# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 43c829d5d308aadd4b40da8b6515fcedc5f0bddaa7f18322d69fe22a93fb46d145fefa0c88ac031ee058aabfc052f214640a474631cb363b61437fa2e47778ec

test:
  secret_key_base: e52ffb709936871bb05458ff260eb8b4b6b64eeac6378fdaa08bf6e02d595014b28235dc6b6b5f64bb8631005c01097ad19e2e1eaa1809113209c0ad6c6f46bd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
